#pragma kernel CSMain

struct VertexData
{
    float3 position;
    float3 normal;
    float2 uv;
};

RWStructuredBuffer<VertexData> _VertexBuffer;
float _Time;
float _Speed;
float _Amplitude;

[numthreads(32,1,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float3 position = _VertexBuffer[id.x].position;
    const float distance = 6.0 - length(position - float3(0, 0, 0));
    position.y = sin(_Time * _Speed + distance) * _Amplitude;
    _VertexBuffer[id.x].position.y = position.y;
}
